Repository googleapis/java-channel, pull requests merged in 2021-01, with the labels that each got.

#9 fix: resolve dependency issue
  grpc-google-cloud-channel-v1/pom.xml
Labels: api: cloudchannel, cla: yes

#11 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#12 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: cloudchannel, automerge, cla: yes

#13 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: cloudchannel, automerge, cla: yes
