Repository googleapis/java-channel, pull requests merged in 2021-02, with the labels that each got.

#26 chore: corrects 'api_id' in repo-metadata.json
  .repo-metadata.json
Labels: api: cloudchannel, automerge, cla: yes

#25 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudchannel, cla: yes, context: partial

#27 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#28 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#23 chore: Re-generated to pick up changes from googleapis.
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.cfg
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceClient.java
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceSettings.java
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/stub/CloudChannelServiceStub.java
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/stub/CloudChannelServiceStubSettings.java
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/stub/GrpcCloudChannelServiceStub.java
  google-cloud-channel/src/test/java/com/google/cloud/channel/v1/CloudChannelServiceClientTest.java
  google-cloud-channel/src/test/java/com/google/cloud/channel/v1/MockCloudChannelServiceImpl.java
  grpc-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceGrpc.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/CustomerEvent.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/CustomerEventOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/EntitlementEvent.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/EntitlementEventOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/ListSubscribersRequest.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/ListSubscribersRequestOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/ListSubscribersResponse.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/ListSubscribersResponseOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/RegisterSubscriberRequest.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/RegisterSubscriberRequestOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/RegisterSubscriberResponse.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/RegisterSubscriberResponseOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/ServiceProto.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/SubscriberEvent.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/SubscriberEventOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/SubscriberEventProto.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/UnregisterSubscriberRequest.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/UnregisterSubscriberRequestOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/UnregisterSubscriberResponse.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/UnregisterSubscriberResponseOrBuilder.java
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/service.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/subscriber_event.proto
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: partial

#30 chore: Re-generated to pick up changes from googleapis
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.cfg
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceClient.java
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/package-info.java
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: partial

#32 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#35 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#34 chore: update gapic-generator-java to 0.0.20
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceClient.java
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/stub/GrpcCloudChannelServiceStub.java
  google-cloud-channel/src/test/java/com/google/cloud/channel/v1/CloudChannelServiceClientTest.java
  google-cloud-channel/src/test/java/com/google/cloud/channel/v1/MockCloudChannelServiceImpl.java
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#36 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#37 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#38 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#43 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/gapic_metadata.json
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#44 feat: deprecate TransferableSkus field
  google-cloud-channel/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceClient.java
  google-cloud-channel/src/test/java/com/google/cloud/channel/v1/CloudChannelServiceClientTest.java
  grpc-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/CloudChannelServiceGrpc.java
  proto-google-cloud-channel-v1/clirr-ignored-differences.xml
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/CreateChannelPartnerLinkRequest.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/CreateChannelPartnerLinkRequestOrBuilder.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/EntitlementsProto.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/ServiceProto.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/TransferableSku.java
  proto-google-cloud-channel-v1/src/main/java/com/google/cloud/channel/v1/TransferableSkuOrBuilder.java
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/channel_partner_links.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/common.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/customers.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/entitlements.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/offers.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/operations.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/products.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/service.proto
  proto-google-cloud-channel-v1/src/main/proto/google/cloud/channel/v1/subscriber_event.proto
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full
