Repository googleapis/java-channel, pull requests merged in 2021-05, with the labels that each got.

#86 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: none

#87 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudchannel, automerge, cla: yes

#88 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudchannel, cla: yes, context: full

#95 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#96 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudchannel, automerge, cla: yes, kokoro:force-run

#97 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#99 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#102 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudchannel, automerge, cla: yes, context: full

#104 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudchannel, automerge, cla: yes
